version: '3.8'

services:
  app:
    build: .
    container_name: wallet-app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${DATASOURCE_DB}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - ${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: